# Generated by Django 5.2 on 2025-04-28 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_location', models.FileField(upload_to='pdfs/')),
                ('json_location', models.FileField(upload_to='json_data/')),
                ('about', models.TextField(blank=True, null=True)),
                ('number_of_fields', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_questions', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('curr_page', models.IntegerField()),
                ('curr_question', models.IntegerField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=20)),
                ('answer', models.TextField()),
                ('question_number', models.IntegerField()),
                ('table_col', models.IntegerField()),
                ('table_row', models.IntegerField()),
                ('question_page', models.IntegerField(blank=True, null=True)),
                ('userform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.userform')),
            ],
        ),
    ]
