# Generated by Django 5.1.5 on 2025-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfield',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
