# Generated by Django 5.2 on 2025-05-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vendor_resourceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceorder',
            name='pdf_location',
            field=models.FileField(null=True, upload_to='ResourceOrders/'),
        ),
    ]
