# Generated by Django 5.2 on 2025-06-13 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_no', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitation_no', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitor_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contractring_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('naics', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('contractor_tel', models.CharField(blank=True, max_length=100, null=True)),
                ('award_date', models.CharField(blank=True, max_length=100, null=True)),
                ('contractor_signed_date', models.CharField(blank=True, max_length=100, null=True)),
                ('officer_signed_date', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_date', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_DBA', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_UEI', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_EFT', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdf_location', models.FileField(null=True, upload_to='Agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
