# Generated by Django 5.2 on 2025-06-13 22:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_location',
            field=models.FileField(null=True, upload_to=main.models.unique_file_upload_path),
        ),
    ]
