# Generated by Django 5.2 on 2025-06-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractor_no',
        ),
    ]
