# Generated by Django 5.2 on 2025-06-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_contract_contractor_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
