# Generated by Django 5.2 on 2025-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contract_contract_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='clin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
